train_data:
  questions: 'v2_OpenEnded_mscoco_train2014_questions.json'
  answers: 'v2_mscoco_train2014_annotations.json'
  features_path: 'train2014_vit_features_w_global_pool'
  raw_features_path: 'train2014_vit_features_raw'
  images_path: 'train2014'
  save_ans_vocab: True

validation_data:
  questions: 'v2_OpenEnded_mscoco_val2014_questions.json'
  answers: 'v2_mscoco_val2014_annotations.json'
  features_path: 'val2014_vit_features_w_global_pool'
  raw_features_path: 'val2014_vit_features_raw'
  images_path: 'val2014'
  save_ans_vocab: False

dataset_path: 'dataset'
embeddings_path: 'embeddings'
ans_vocab_path: 'answer_vocab.json'
glove_embs: 'glove.6B.300d.txt'
embeddings: 'embeddings_glove.6B.300d.npy'
vocab: 'vocab_glove.6B.300d.npy'
with_global_pool: False
max_seq_length: 24
min_count_threshold: 10
batch_size: 16
epochs: 50
top_classes: 5